name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate version file
        run: npm run version-file

      - name: Build Electron App
        run: npm run build

      - name: Create a release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and release
        id: tag
        run: |
          VERSION=$(cat version.txt)
          echo "Version: $VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"
